services:
  - type: web
    name: python-ml-microservice
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: PORT
        value: 5002
      - key: HF_MODEL_NAME
        value: distilbert-base-uncased
    autoDeploy: true 